language: python
python:
    - "2.7"
    - "2.6"

branches:
    only:
        - master

install:
    - pip install sphinx tox simplejson pylint autopep8
    - pip install inspektor
    - pip install -r requirements.txt
    - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then pip install -r requirements-python26.txt; fi

script:
    - ./selftests/runtests.py -c .nose.cfg
    - inspekt lint
    - inspekt style
